version: "3.7"
services:

  ## PHP-FPM Container
  php-container:
    build:
      context: ./docker/php-fpm
      dockerfile: Dockerfile
    image: php-fpm
    container_name: client-management
    restart: unless-stopped
    working_dir: /var/www/html
    ports:
      - 5173:5173
    volumes:
      - ./:/var/www/html
    networks:
      - client-management-network

  ## NGINX Container
  nginx-container:
    image: nginx:1.19-alpine
    container_name: client-management-nginx
    restart: unless-stopped
    ports:
      - 80:80
    volumes:
      - ./:/var/www/html
      - ./docker/nginx:/etc/nginx/conf.d
    networks:
      - client-management-network

  # MySQL Container
  mysql-container:
    image: mysql:8.0
    container_name: client-management-mysql
    volumes:
      - client-management-v-db:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    networks:
      - client-management-network

networks:
  client-management-network:
    driver: bridge

volumes:
  client-management-v-db:
    driver: local